spring.application.name=ecommerce-app

# server configuration
server.port=8080
server.servlet.context-path=/api

# Database configuration
spring.datasource.url=jbdc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Logging configuration
logging.level.org.springframework=INFO

# Spring Security configuration
spring.security.user.name=admin
spring.security.user.password=admin


# JWT config
secretJwtString = mbas123456789mbas123456789mbas123456789